services:
  web:
    build: .
    container_name: pt-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-1}
      SOLR_URL: ${SOLR_URL:-http://solr:8983/solr/pennstreaty}
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db
      - solr
  db:
    image: postgres:15
    container_name: pt-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pennstreaty}
  solr:
    image: solr:9.3
    container_name: pt-solr
    ports:
     - "8983:8983"
    volumes:
      - ./data/solr:/var/solr
    command: solr-precreate pennstreaty
  proxy:
    image: caddy:2.9
    container_name: pt-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
      - ./caddy-conf/dev:/etc/caddy
      - ./media:/media
      - ./static:/static
    depends_on:
      - web
